# This is a basic workflow to help you get started with Actions

name: heroku-deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # https://github.com/docker/build-push-action
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.HEROKU_USERNAME }}
        password: ${{ secrets.HEROKU_KEY }}
        registry: registry.heroku.com
        # https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image
        repository: registry.heroku.com/yoga1290/web
        path: /home/runner/work/VideoQuotes/VideoQuotes
        dockerfile: Dockerfile.dev
        push: true